# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dmp.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 795)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.page_1)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.frame_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.page_1)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.RobotIPLabel = QtWidgets.QLabel(self.splitter)
        self.RobotIPLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.RobotIPLabel.setObjectName("RobotIPLabel")
        self.IPLineEdit = QtWidgets.QLineEdit(self.splitter)
        self.IPLineEdit.setMaximumSize(QtCore.QSize(16777215, 26))
        self.IPLineEdit.setObjectName("IPLineEdit")
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.simulationCheckBox = QtWidgets.QCheckBox(self.splitter_2)
        self.simulationCheckBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.simulationCheckBox.setObjectName("simulationCheckBox")
        self.gridLayout_4.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.splitter_6 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.label = QtWidgets.QLabel(self.splitter_6)
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setObjectName("label")
        self.ChooseRobotcomboBox = QtWidgets.QComboBox(self.splitter_6)
        self.ChooseRobotcomboBox.setObjectName("ChooseRobotcomboBox")
        self.ChooseRobotcomboBox.addItem("")
        self.ChooseRobotcomboBox.addItem("")
        self.ChooseRobotcomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.splitter_6)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(100, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startButton = QtWidgets.QPushButton(self.frame)
        self.startButton.setMinimumSize(QtCore.QSize(0, 40))
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.start_loadClasses_PB = QtWidgets.QPushButton(self.frame)
        self.start_loadClasses_PB.setMinimumSize(QtCore.QSize(0, 40))
        self.start_loadClasses_PB.setObjectName("start_loadClasses_PB")
        self.verticalLayout.addWidget(self.start_loadClasses_PB)
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout_3.addWidget(self.frame_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_21 = QtWidgets.QFrame(self.page_2)
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_21)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.splitter_12 = QtWidgets.QSplitter(self.frame_21)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.Tab = QtWidgets.QTabWidget(self.splitter_12)
        self.Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tab.setObjectName("Tab")
        self.Recording_tab = QtWidgets.QWidget()
        self.Recording_tab.setObjectName("Recording_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Recording_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_7 = QtWidgets.QSplitter(self.Recording_tab)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.label_15 = QtWidgets.QLabel(self.splitter_7)
        self.label_15.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_15.setObjectName("label_15")
        self.name_recording_line_edit = QtWidgets.QLineEdit(self.splitter_7)
        self.name_recording_line_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.name_recording_line_edit.setText("")
        self.name_recording_line_edit.setObjectName("name_recording_line_edit")
        self.verticalLayout_3.addWidget(self.splitter_7)
        self.frame_22 = QtWidgets.QFrame(self.Recording_tab)
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.splitter_3 = QtWidgets.QSplitter(self.frame_23)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.frame_7 = QtWidgets.QFrame(self.splitter_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.rec_EE_radio_button = QtWidgets.QRadioButton(self.frame_7)
        self.rec_EE_radio_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.rec_EE_radio_button.setObjectName("rec_EE_radio_button")
        self.gridLayout_8.addWidget(self.rec_EE_radio_button, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 199))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 1, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.splitter_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_9 = QtWidgets.QSplitter(self.frame_8)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.rec_JS_radio_button = QtWidgets.QRadioButton(self.splitter_9)
        self.rec_JS_radio_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.rec_JS_radio_button.setObjectName("rec_JS_radio_button")
        self.label_3 = QtWidgets.QLabel(self.splitter_9)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 199))
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.splitter_9, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_23)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.start_recording_button = QtWidgets.QPushButton(self.frame_22)
        self.start_recording_button.setMinimumSize(QtCore.QSize(0, 40))
        self.start_recording_button.setObjectName("start_recording_button")
        self.verticalLayout_4.addWidget(self.start_recording_button)
        self.stop_recording_button = QtWidgets.QPushButton(self.frame_22)
        self.stop_recording_button.setMinimumSize(QtCore.QSize(0, 40))
        self.stop_recording_button.setObjectName("stop_recording_button")
        self.verticalLayout_4.addWidget(self.stop_recording_button)
        self.verticalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.frame_22)
        self.Tab.addTab(self.Recording_tab, "")
        self.Generate_tab = QtWidgets.QWidget()
        self.Generate_tab.setObjectName("Generate_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Generate_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_26 = QtWidgets.QFrame(self.Generate_tab)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_22 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_15.addWidget(self.label_22)
        self.load_EE_rec_radio_button = QtWidgets.QRadioButton(self.frame_26)
        self.load_EE_rec_radio_button.setObjectName("load_EE_rec_radio_button")
        self.verticalLayout_15.addWidget(self.load_EE_rec_radio_button)
        self.load_JS_rec_radio_button = QtWidgets.QRadioButton(self.frame_26)
        self.load_JS_rec_radio_button.setObjectName("load_JS_rec_radio_button")
        self.verticalLayout_15.addWidget(self.load_JS_rec_radio_button)
        self.verticalLayout_6.addWidget(self.frame_26)
        self.frame_24 = QtWidgets.QFrame(self.Generate_tab)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_24)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.splitter_13 = QtWidgets.QSplitter(self.frame_24)
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName("splitter_13")
        self.label_16 = QtWidgets.QLabel(self.splitter_13)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        self.label_16.setObjectName("label_16")
        self.dmp_dt_param_lineedit = QtWidgets.QLineEdit(self.splitter_13)
        self.dmp_dt_param_lineedit.setObjectName("dmp_dt_param_lineedit")
        self.verticalLayout_5.addWidget(self.splitter_13)
        self.splitter_14 = QtWidgets.QSplitter(self.frame_24)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.label_17 = QtWidgets.QLabel(self.splitter_14)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        self.label_17.setObjectName("label_17")
        self.dmp_K_param_lineedit = QtWidgets.QLineEdit(self.splitter_14)
        self.dmp_K_param_lineedit.setObjectName("dmp_K_param_lineedit")
        self.verticalLayout_5.addWidget(self.splitter_14)
        self.splitter_15 = QtWidgets.QSplitter(self.frame_24)
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName("splitter_15")
        self.label_18 = QtWidgets.QLabel(self.splitter_15)
        self.label_18.setMinimumSize(QtCore.QSize(100, 0))
        self.label_18.setObjectName("label_18")
        self.dmp_D_param_lineedit = QtWidgets.QLineEdit(self.splitter_15)
        self.dmp_D_param_lineedit.setObjectName("dmp_D_param_lineedit")
        self.verticalLayout_5.addWidget(self.splitter_15)
        self.splitter_16 = QtWidgets.QSplitter(self.frame_24)
        self.splitter_16.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_16.setObjectName("splitter_16")
        self.label_19 = QtWidgets.QLabel(self.splitter_16)
        self.label_19.setMinimumSize(QtCore.QSize(100, 0))
        self.label_19.setObjectName("label_19")
        self.dmp_basisfunc_param_lineedit = QtWidgets.QLineEdit(self.splitter_16)
        self.dmp_basisfunc_param_lineedit.setObjectName("dmp_basisfunc_param_lineedit")
        self.verticalLayout_5.addWidget(self.splitter_16)
        self.verticalLayout_6.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.Generate_tab)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_25)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_5 = QtWidgets.QSplitter(self.frame_25)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_20 = QtWidgets.QLabel(self.splitter_5)
        self.label_20.setObjectName("label_20")
        self.load_name_rec_comboBox = QtWidgets.QComboBox(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_name_rec_comboBox.sizePolicy().hasHeightForWidth())
        self.load_name_rec_comboBox.setSizePolicy(sizePolicy)
        self.load_name_rec_comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.load_name_rec_comboBox.setEditable(True)
        self.load_name_rec_comboBox.setObjectName("load_name_rec_comboBox")
        self.gridLayout_2.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.splitter_18 = QtWidgets.QSplitter(self.frame_25)
        self.splitter_18.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_18.setObjectName("splitter_18")
        self.label_21 = QtWidgets.QLabel(self.splitter_18)
        self.label_21.setObjectName("label_21")
        self.save_name_dmp_lineedit = QtWidgets.QLineEdit(self.splitter_18)
        self.save_name_dmp_lineedit.setText("")
        self.save_name_dmp_lineedit.setObjectName("save_name_dmp_lineedit")
        self.gridLayout_2.addWidget(self.splitter_18, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_25)
        self.frame_27 = QtWidgets.QFrame(self.Generate_tab)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.generate_DMP_button = QtWidgets.QPushButton(self.frame_27)
        self.generate_DMP_button.setObjectName("generate_DMP_button")
        self.verticalLayout_16.addWidget(self.generate_DMP_button)
        self.verticalLayout_6.addWidget(self.frame_27)
        self.Tab.addTab(self.Generate_tab, "")
        self.Execute_tab = QtWidgets.QWidget()
        self.Execute_tab.setObjectName("Execute_tab")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.Execute_tab)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.frame_28 = QtWidgets.QFrame(self.Execute_tab)
        self.frame_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setLineWidth(0)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter_19 = QtWidgets.QSplitter(self.frame_28)
        self.splitter_19.setOrientation(QtCore.Qt.Vertical)
        self.splitter_19.setObjectName("splitter_19")
        self.frame_29 = QtWidgets.QFrame(self.splitter_19)
        self.frame_29.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_29)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_23 = QtWidgets.QLabel(self.frame_29)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 0, 0, 1, 1)
        self.set_DMP_comboBox = QtWidgets.QComboBox(self.frame_29)
        self.set_DMP_comboBox.setMinimumSize(QtCore.QSize(200, 25))
        self.set_DMP_comboBox.setObjectName("set_DMP_comboBox")
        self.gridLayout_7.addWidget(self.set_DMP_comboBox, 0, 1, 1, 1)
        self.set_active_DMP_pushButton = QtWidgets.QPushButton(self.frame_29)
        self.set_active_DMP_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.set_active_DMP_pushButton.setObjectName("set_active_DMP_pushButton")
        self.gridLayout_7.addWidget(self.set_active_DMP_pushButton, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_19)
        self.tabWidget.setObjectName("tabWidget")
        self.jointspace_2 = QtWidgets.QWidget()
        self.jointspace_2.setObjectName("jointspace_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.jointspace_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_32 = QtWidgets.QFrame(self.jointspace_2)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_25 = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_7.addWidget(self.label_25)
        self.splitter_11 = QtWidgets.QSplitter(self.frame_32)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.label_6 = QtWidgets.QLabel(self.splitter_11)
        self.label_6.setObjectName("label_6")
        self.set_JointState_init_0_lineEdit = QtWidgets.QLineEdit(self.splitter_11)
        self.set_JointState_init_0_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_init_0_lineEdit.setMaxLength(6)
        self.set_JointState_init_0_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_init_0_lineEdit.setObjectName("set_JointState_init_0_lineEdit")
        self.verticalLayout_7.addWidget(self.splitter_11)
        self.splitter_17 = QtWidgets.QSplitter(self.frame_32)
        self.splitter_17.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_17.setObjectName("splitter_17")
        self.label_8 = QtWidgets.QLabel(self.splitter_17)
        self.label_8.setObjectName("label_8")
        self.set_JointState_init_1_lineEdit = QtWidgets.QLineEdit(self.splitter_17)
        self.set_JointState_init_1_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_init_1_lineEdit.setMaxLength(6)
        self.set_JointState_init_1_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_init_1_lineEdit.setObjectName("set_JointState_init_1_lineEdit")
        self.verticalLayout_7.addWidget(self.splitter_17)
        self.splitter_28 = QtWidgets.QSplitter(self.frame_32)
        self.splitter_28.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_28.setObjectName("splitter_28")
        self.label_9 = QtWidgets.QLabel(self.splitter_28)
        self.label_9.setObjectName("label_9")
        self.set_JointState_init_2_lineEdit = QtWidgets.QLineEdit(self.splitter_28)
        self.set_JointState_init_2_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_init_2_lineEdit.setMaxLength(6)
        self.set_JointState_init_2_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_init_2_lineEdit.setObjectName("set_JointState_init_2_lineEdit")
        self.verticalLayout_7.addWidget(self.splitter_28)
        self.splitter_29 = QtWidgets.QSplitter(self.frame_32)
        self.splitter_29.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_29.setObjectName("splitter_29")
        self.label_10 = QtWidgets.QLabel(self.splitter_29)
        self.label_10.setObjectName("label_10")
        self.set_JointState_init_3_lineEdit = QtWidgets.QLineEdit(self.splitter_29)
        self.set_JointState_init_3_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_init_3_lineEdit.setMaxLength(6)
        self.set_JointState_init_3_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_init_3_lineEdit.setObjectName("set_JointState_init_3_lineEdit")
        self.verticalLayout_7.addWidget(self.splitter_29)
        self.splitter_21 = QtWidgets.QSplitter(self.frame_32)
        self.splitter_21.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_21.setObjectName("splitter_21")
        self.label_11 = QtWidgets.QLabel(self.splitter_21)
        self.label_11.setObjectName("label_11")
        self.set_JointState_init_4_lineEdit = QtWidgets.QLineEdit(self.splitter_21)
        self.set_JointState_init_4_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_init_4_lineEdit.setMaxLength(6)
        self.set_JointState_init_4_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_init_4_lineEdit.setObjectName("set_JointState_init_4_lineEdit")
        self.verticalLayout_7.addWidget(self.splitter_21)
        self.splitter_20 = QtWidgets.QSplitter(self.frame_32)
        self.splitter_20.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_20.setObjectName("splitter_20")
        self.label_12 = QtWidgets.QLabel(self.splitter_20)
        self.label_12.setObjectName("label_12")
        self.set_JointState_init_5_lineEdit = QtWidgets.QLineEdit(self.splitter_20)
        self.set_JointState_init_5_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_init_5_lineEdit.setMaxLength(6)
        self.set_JointState_init_5_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_init_5_lineEdit.setObjectName("set_JointState_init_5_lineEdit")
        self.verticalLayout_7.addWidget(self.splitter_20)
        self.get_JS_init_robot_pushButton = QtWidgets.QPushButton(self.frame_32)
        self.get_JS_init_robot_pushButton.setObjectName("get_JS_init_robot_pushButton")
        self.verticalLayout_7.addWidget(self.get_JS_init_robot_pushButton)
        self.horizontalLayout_2.addWidget(self.frame_32)
        self.frame_33 = QtWidgets.QFrame(self.jointspace_2)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_26 = QtWidgets.QLabel(self.frame_33)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_8.addWidget(self.label_26)
        self.splitter_22 = QtWidgets.QSplitter(self.frame_33)
        self.splitter_22.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_22.setObjectName("splitter_22")
        self.label_14 = QtWidgets.QLabel(self.splitter_22)
        self.label_14.setObjectName("label_14")
        self.set_JointState_goal_0_lineEdit = QtWidgets.QLineEdit(self.splitter_22)
        self.set_JointState_goal_0_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_goal_0_lineEdit.setMaxLength(6)
        self.set_JointState_goal_0_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_goal_0_lineEdit.setObjectName("set_JointState_goal_0_lineEdit")
        self.verticalLayout_8.addWidget(self.splitter_22)
        self.splitter_23 = QtWidgets.QSplitter(self.frame_33)
        self.splitter_23.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_23.setObjectName("splitter_23")
        self.label_13 = QtWidgets.QLabel(self.splitter_23)
        self.label_13.setObjectName("label_13")
        self.set_JointState_goal_1_lineEdit = QtWidgets.QLineEdit(self.splitter_23)
        self.set_JointState_goal_1_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_goal_1_lineEdit.setMaxLength(6)
        self.set_JointState_goal_1_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_goal_1_lineEdit.setObjectName("set_JointState_goal_1_lineEdit")
        self.verticalLayout_8.addWidget(self.splitter_23)
        self.splitter_24 = QtWidgets.QSplitter(self.frame_33)
        self.splitter_24.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_24.setObjectName("splitter_24")
        self.label_30 = QtWidgets.QLabel(self.splitter_24)
        self.label_30.setObjectName("label_30")
        self.set_JointState_goal_2_lineEdit = QtWidgets.QLineEdit(self.splitter_24)
        self.set_JointState_goal_2_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_goal_2_lineEdit.setMaxLength(6)
        self.set_JointState_goal_2_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_goal_2_lineEdit.setObjectName("set_JointState_goal_2_lineEdit")
        self.verticalLayout_8.addWidget(self.splitter_24)
        self.splitter_25 = QtWidgets.QSplitter(self.frame_33)
        self.splitter_25.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_25.setObjectName("splitter_25")
        self.label_31 = QtWidgets.QLabel(self.splitter_25)
        self.label_31.setObjectName("label_31")
        self.set_JointState_goal_3_lineEdit = QtWidgets.QLineEdit(self.splitter_25)
        self.set_JointState_goal_3_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_goal_3_lineEdit.setMaxLength(6)
        self.set_JointState_goal_3_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_goal_3_lineEdit.setObjectName("set_JointState_goal_3_lineEdit")
        self.verticalLayout_8.addWidget(self.splitter_25)
        self.splitter_26 = QtWidgets.QSplitter(self.frame_33)
        self.splitter_26.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_26.setObjectName("splitter_26")
        self.label_29 = QtWidgets.QLabel(self.splitter_26)
        self.label_29.setObjectName("label_29")
        self.set_JointState_goal_4_lineEdit = QtWidgets.QLineEdit(self.splitter_26)
        self.set_JointState_goal_4_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_goal_4_lineEdit.setMaxLength(6)
        self.set_JointState_goal_4_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_goal_4_lineEdit.setObjectName("set_JointState_goal_4_lineEdit")
        self.verticalLayout_8.addWidget(self.splitter_26)
        self.splitter_27 = QtWidgets.QSplitter(self.frame_33)
        self.splitter_27.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_27.setObjectName("splitter_27")
        self.label_32 = QtWidgets.QLabel(self.splitter_27)
        self.label_32.setObjectName("label_32")
        self.set_JointState_goal_5_lineEdit = QtWidgets.QLineEdit(self.splitter_27)
        self.set_JointState_goal_5_lineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.set_JointState_goal_5_lineEdit.setMaxLength(6)
        self.set_JointState_goal_5_lineEdit.setClearButtonEnabled(False)
        self.set_JointState_goal_5_lineEdit.setObjectName("set_JointState_goal_5_lineEdit")
        self.verticalLayout_8.addWidget(self.splitter_27)
        self.get_JS_goal_robot_pushButton = QtWidgets.QPushButton(self.frame_33)
        self.get_JS_goal_robot_pushButton.setObjectName("get_JS_goal_robot_pushButton")
        self.verticalLayout_8.addWidget(self.get_JS_goal_robot_pushButton)
        self.horizontalLayout_2.addWidget(self.frame_33)
        self.tabWidget.addTab(self.jointspace_2, "")
        self.cartesianSpace_2 = QtWidgets.QWidget()
        self.cartesianSpace_2.setObjectName("cartesianSpace_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.cartesianSpace_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.cartesianSpace_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_27 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_9.addWidget(self.label_27)
        self.splitter_30 = QtWidgets.QSplitter(self.frame_6)
        self.splitter_30.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_30.setObjectName("splitter_30")
        self.label_7 = QtWidgets.QLabel(self.splitter_30)
        self.label_7.setObjectName("label_7")
        self.set_CS_init_tx_lineEdit = QtWidgets.QLineEdit(self.splitter_30)
        self.set_CS_init_tx_lineEdit.setMaxLength(6)
        self.set_CS_init_tx_lineEdit.setClearButtonEnabled(False)
        self.set_CS_init_tx_lineEdit.setObjectName("set_CS_init_tx_lineEdit")
        self.verticalLayout_9.addWidget(self.splitter_30)
        self.splitter_31 = QtWidgets.QSplitter(self.frame_6)
        self.splitter_31.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_31.setObjectName("splitter_31")
        self.label_33 = QtWidgets.QLabel(self.splitter_31)
        self.label_33.setObjectName("label_33")
        self.set_CS_init_ty_lineEdit = QtWidgets.QLineEdit(self.splitter_31)
        self.set_CS_init_ty_lineEdit.setMaxLength(6)
        self.set_CS_init_ty_lineEdit.setClearButtonEnabled(False)
        self.set_CS_init_ty_lineEdit.setObjectName("set_CS_init_ty_lineEdit")
        self.verticalLayout_9.addWidget(self.splitter_31)
        self.splitter_39 = QtWidgets.QSplitter(self.frame_6)
        self.splitter_39.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_39.setObjectName("splitter_39")
        self.label_34 = QtWidgets.QLabel(self.splitter_39)
        self.label_34.setObjectName("label_34")
        self.set_CS_init_tz_lineEdit = QtWidgets.QLineEdit(self.splitter_39)
        self.set_CS_init_tz_lineEdit.setMaxLength(6)
        self.set_CS_init_tz_lineEdit.setClearButtonEnabled(False)
        self.set_CS_init_tz_lineEdit.setObjectName("set_CS_init_tz_lineEdit")
        self.verticalLayout_9.addWidget(self.splitter_39)
        self.splitter_40 = QtWidgets.QSplitter(self.frame_6)
        self.splitter_40.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_40.setObjectName("splitter_40")
        self.label_35 = QtWidgets.QLabel(self.splitter_40)
        self.label_35.setObjectName("label_35")
        self.set_CS_init_rx_lineEdit = QtWidgets.QLineEdit(self.splitter_40)
        self.set_CS_init_rx_lineEdit.setMaxLength(6)
        self.set_CS_init_rx_lineEdit.setClearButtonEnabled(False)
        self.set_CS_init_rx_lineEdit.setObjectName("set_CS_init_rx_lineEdit")
        self.verticalLayout_9.addWidget(self.splitter_40)
        self.splitter_41 = QtWidgets.QSplitter(self.frame_6)
        self.splitter_41.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_41.setObjectName("splitter_41")
        self.label_36 = QtWidgets.QLabel(self.splitter_41)
        self.label_36.setObjectName("label_36")
        self.set_CS_init_ry_lineEdit = QtWidgets.QLineEdit(self.splitter_41)
        self.set_CS_init_ry_lineEdit.setMaxLength(6)
        self.set_CS_init_ry_lineEdit.setClearButtonEnabled(False)
        self.set_CS_init_ry_lineEdit.setObjectName("set_CS_init_ry_lineEdit")
        self.verticalLayout_9.addWidget(self.splitter_41)
        self.splitter_42 = QtWidgets.QSplitter(self.frame_6)
        self.splitter_42.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_42.setObjectName("splitter_42")
        self.label_37 = QtWidgets.QLabel(self.splitter_42)
        self.label_37.setObjectName("label_37")
        self.set_CS_init_rz_lineEdit = QtWidgets.QLineEdit(self.splitter_42)
        self.set_CS_init_rz_lineEdit.setMaxLength(6)
        self.set_CS_init_rz_lineEdit.setClearButtonEnabled(False)
        self.set_CS_init_rz_lineEdit.setObjectName("set_CS_init_rz_lineEdit")
        self.verticalLayout_9.addWidget(self.splitter_42)
        self.splitter_43 = QtWidgets.QSplitter(self.frame_6)
        self.splitter_43.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_43.setObjectName("splitter_43")
        self.label_38 = QtWidgets.QLabel(self.splitter_43)
        self.label_38.setObjectName("label_38")
        self.set_CS_init_w_lineEdit = QtWidgets.QLineEdit(self.splitter_43)
        self.set_CS_init_w_lineEdit.setMaxLength(6)
        self.set_CS_init_w_lineEdit.setClearButtonEnabled(False)
        self.set_CS_init_w_lineEdit.setObjectName("set_CS_init_w_lineEdit")
        self.verticalLayout_9.addWidget(self.splitter_43)
        self.get_CS_init_robot_PB = QtWidgets.QPushButton(self.frame_6)
        self.get_CS_init_robot_PB.setObjectName("get_CS_init_robot_PB")
        self.verticalLayout_9.addWidget(self.get_CS_init_robot_PB)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_35 = QtWidgets.QFrame(self.cartesianSpace_2)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_28 = QtWidgets.QLabel(self.frame_35)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_10.addWidget(self.label_28)
        self.splitter_32 = QtWidgets.QSplitter(self.frame_35)
        self.splitter_32.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_32.setObjectName("splitter_32")
        self.label_42 = QtWidgets.QLabel(self.splitter_32)
        self.label_42.setObjectName("label_42")
        self.set_CS_goal_tx_lineEdit = QtWidgets.QLineEdit(self.splitter_32)
        self.set_CS_goal_tx_lineEdit.setMaxLength(6)
        self.set_CS_goal_tx_lineEdit.setClearButtonEnabled(False)
        self.set_CS_goal_tx_lineEdit.setObjectName("set_CS_goal_tx_lineEdit")
        self.verticalLayout_10.addWidget(self.splitter_32)
        self.splitter_33 = QtWidgets.QSplitter(self.frame_35)
        self.splitter_33.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_33.setObjectName("splitter_33")
        self.label_45 = QtWidgets.QLabel(self.splitter_33)
        self.label_45.setObjectName("label_45")
        self.set_CS_goal_ty_lineEdit = QtWidgets.QLineEdit(self.splitter_33)
        self.set_CS_goal_ty_lineEdit.setMaxLength(6)
        self.set_CS_goal_ty_lineEdit.setClearButtonEnabled(False)
        self.set_CS_goal_ty_lineEdit.setObjectName("set_CS_goal_ty_lineEdit")
        self.verticalLayout_10.addWidget(self.splitter_33)
        self.splitter_34 = QtWidgets.QSplitter(self.frame_35)
        self.splitter_34.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_34.setObjectName("splitter_34")
        self.label_41 = QtWidgets.QLabel(self.splitter_34)
        self.label_41.setObjectName("label_41")
        self.set_CS_goal_tz_lineEdit = QtWidgets.QLineEdit(self.splitter_34)
        self.set_CS_goal_tz_lineEdit.setMaxLength(6)
        self.set_CS_goal_tz_lineEdit.setClearButtonEnabled(False)
        self.set_CS_goal_tz_lineEdit.setObjectName("set_CS_goal_tz_lineEdit")
        self.verticalLayout_10.addWidget(self.splitter_34)
        self.splitter_35 = QtWidgets.QSplitter(self.frame_35)
        self.splitter_35.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_35.setObjectName("splitter_35")
        self.label_40 = QtWidgets.QLabel(self.splitter_35)
        self.label_40.setObjectName("label_40")
        self.set_CS_goal_rx_lineEdit = QtWidgets.QLineEdit(self.splitter_35)
        self.set_CS_goal_rx_lineEdit.setMaxLength(6)
        self.set_CS_goal_rx_lineEdit.setClearButtonEnabled(False)
        self.set_CS_goal_rx_lineEdit.setObjectName("set_CS_goal_rx_lineEdit")
        self.verticalLayout_10.addWidget(self.splitter_35)
        self.splitter_36 = QtWidgets.QSplitter(self.frame_35)
        self.splitter_36.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_36.setObjectName("splitter_36")
        self.label_44 = QtWidgets.QLabel(self.splitter_36)
        self.label_44.setObjectName("label_44")
        self.set_CS_goal_ry_lineEdit = QtWidgets.QLineEdit(self.splitter_36)
        self.set_CS_goal_ry_lineEdit.setMaxLength(6)
        self.set_CS_goal_ry_lineEdit.setClearButtonEnabled(False)
        self.set_CS_goal_ry_lineEdit.setObjectName("set_CS_goal_ry_lineEdit")
        self.verticalLayout_10.addWidget(self.splitter_36)
        self.splitter_37 = QtWidgets.QSplitter(self.frame_35)
        self.splitter_37.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_37.setObjectName("splitter_37")
        self.label_39 = QtWidgets.QLabel(self.splitter_37)
        self.label_39.setObjectName("label_39")
        self.set_CS_goal_rz_lineEdit = QtWidgets.QLineEdit(self.splitter_37)
        self.set_CS_goal_rz_lineEdit.setMaxLength(6)
        self.set_CS_goal_rz_lineEdit.setClearButtonEnabled(False)
        self.set_CS_goal_rz_lineEdit.setObjectName("set_CS_goal_rz_lineEdit")
        self.verticalLayout_10.addWidget(self.splitter_37)
        self.splitter_38 = QtWidgets.QSplitter(self.frame_35)
        self.splitter_38.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_38.setObjectName("splitter_38")
        self.label_43 = QtWidgets.QLabel(self.splitter_38)
        self.label_43.setObjectName("label_43")
        self.set_CS_goal_w_lineEdit = QtWidgets.QLineEdit(self.splitter_38)
        self.set_CS_goal_w_lineEdit.setMaxLength(6)
        self.set_CS_goal_w_lineEdit.setClearButtonEnabled(False)
        self.set_CS_goal_w_lineEdit.setObjectName("set_CS_goal_w_lineEdit")
        self.verticalLayout_10.addWidget(self.splitter_38)
        self.get_CS_goal_robot_PB = QtWidgets.QPushButton(self.frame_35)
        self.get_CS_goal_robot_PB.setObjectName("get_CS_goal_robot_PB")
        self.verticalLayout_10.addWidget(self.get_CS_goal_robot_PB)
        self.horizontalLayout_4.addWidget(self.frame_35)
        self.tabWidget.addTab(self.cartesianSpace_2, "")
        self.frame_31 = QtWidgets.QFrame(self.splitter_19)
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_31)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame_36 = QtWidgets.QFrame(self.frame_31)
        self.frame_36.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_36.setObjectName("frame_36")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_36)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.execute_plan_pushButton = QtWidgets.QPushButton(self.frame_36)
        self.execute_plan_pushButton.setObjectName("execute_plan_pushButton")
        self.gridLayout_30.addWidget(self.execute_plan_pushButton, 1, 0, 1, 1)
        self.execute_collisionCheck_PB = QtWidgets.QPushButton(self.frame_36)
        self.execute_collisionCheck_PB.setObjectName("execute_collisionCheck_PB")
        self.gridLayout_30.addWidget(self.execute_collisionCheck_PB, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frame_36, 1, 0, 1, 1)
        self.frame_30 = QtWidgets.QFrame(self.frame_31)
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.splitter_4 = QtWidgets.QSplitter(self.frame_30)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_24 = QtWidgets.QLabel(self.splitter_4)
        self.label_24.setObjectName("label_24")
        self.set_tau_lineedit = QtWidgets.QLineEdit(self.splitter_4)
        self.set_tau_lineedit.setMaximumSize(QtCore.QSize(16777215, 28))
        self.set_tau_lineedit.setClearButtonEnabled(False)
        self.set_tau_lineedit.setObjectName("set_tau_lineedit")
        self.verticalLayout_11.addWidget(self.splitter_4)
        self.gridLayout_23.addWidget(self.frame_30, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.splitter_19)
        self.frame_5 = QtWidgets.QFrame(self.frame_28)
        self.frame_5.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.space_for_rviz = QtWidgets.QWidget(self.frame_5)
        self.space_for_rviz.setMinimumSize(QtCore.QSize(0, 0))
        self.space_for_rviz.setObjectName("space_for_rviz")
        self.gridLayout_6.addWidget(self.space_for_rviz, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.gridLayout_31.addWidget(self.frame_28, 0, 1, 1, 1)
        self.Tab.addTab(self.Execute_tab, "")
        self.Settings_tab = QtWidgets.QWidget()
        self.Settings_tab.setObjectName("Settings_tab")
        self.splitter_8 = QtWidgets.QSplitter(self.Settings_tab)
        self.splitter_8.setGeometry(QtCore.QRect(40, 40, 257, 25))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.label_4 = QtWidgets.QLabel(self.splitter_8)
        self.label_4.setObjectName("label_4")
        self.recording_folder_LE = QtWidgets.QLineEdit(self.splitter_8)
        self.recording_folder_LE.setObjectName("recording_folder_LE")
        self.splitter_10 = QtWidgets.QSplitter(self.Settings_tab)
        self.splitter_10.setGeometry(QtCore.QRect(50, 90, 243, 25))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.label_46 = QtWidgets.QLabel(self.splitter_10)
        self.label_46.setObjectName("label_46")
        self.weight_folder_LE = QtWidgets.QLineEdit(self.splitter_10)
        self.weight_folder_LE.setObjectName("weight_folder_LE")
        self.Tab.addTab(self.Settings_tab, "")
        self.gridLayout_13.addWidget(self.splitter_12, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_21, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_12.addWidget(self.stackedWidget)
        self.shutDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.shutDownButton.setMinimumSize(QtCore.QSize(0, 40))
        self.shutDownButton.setObjectName("shutDownButton")
        self.verticalLayout_12.addWidget(self.shutDownButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.menuFile.addAction(self.actionHome)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.Tab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">Welcome to my robot DMP application.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The goal of this application is reduce the steppingstone that non-experts has to start working with robots. Ths is done by implementing Dynamic Movement Primitives and combine them with an intuitiv graphical user interface. The application is currently developed for use on Universal Robots, and have been testet on the UR3. It can be used both on real robots and in a simulation.</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This application is developed as a part of my Master thesis at Universitat Politecnica de Catalunya .</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Author: Roy Ove Eriksen</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Date: Autumn 2020</p></body></html>"))
        self.RobotIPLabel.setText(_translate("MainWindow", "Robot IP:"))
        self.IPLineEdit.setPlaceholderText(_translate("MainWindow", "192.168.1.128"))
        self.simulationCheckBox.setText(_translate("MainWindow", "Simulation"))
        self.label.setText(_translate("MainWindow", "Robots:"))
        self.ChooseRobotcomboBox.setItemText(0, _translate("MainWindow", "UR3"))
        self.ChooseRobotcomboBox.setItemText(1, _translate("MainWindow", "UR5"))
        self.ChooseRobotcomboBox.setItemText(2, _translate("MainWindow", "UR10"))
        self.startButton.setText(_translate("MainWindow", "Connect to Robot"))
        self.start_loadClasses_PB.setText(_translate("MainWindow", "Start DMP application"))
        self.label_15.setText(_translate("MainWindow", "Name of recording:"))
        self.rec_EE_radio_button.setText(_translate("MainWindow", "End-Effector"))
        self.label_2.setText(_translate("MainWindow", "Records the pose of the end-effector. This takes as input a ROS Pose( Position and Orientation in quaternion)\n"
" and are listning on the topic /end_effector_pose\n"
" To use this feature an external source needs to publish to the /end_effector_pose topic"))
        self.rec_JS_radio_button.setText(_translate("MainWindow", "Joint_States"))
        self.label_3.setText(_translate("MainWindow", "Records joint values in radians that are published by the robot_state_publisher on topic /joint_states\n"
" The recordings are saved as Rosbags in the /Data/rosbag_recordings "))
        self.start_recording_button.setText(_translate("MainWindow", "Start"))
        self.stop_recording_button.setText(_translate("MainWindow", "Stop"))
        self.Tab.setTabText(self.Tab.indexOf(self.Recording_tab), _translate("MainWindow", "Recording"))
        self.label_22.setText(_translate("MainWindow", "Type of recording to load"))
        self.load_EE_rec_radio_button.setToolTip(_translate("MainWindow", "<html><head/><body><p>world position of the tool point</p></body></html>"))
        self.load_EE_rec_radio_button.setText(_translate("MainWindow", "End-Effector rec"))
        self.load_JS_rec_radio_button.setText(_translate("MainWindow", "Joint_state rec"))
        self.label_5.setText(_translate("MainWindow", "DMP parameters"))
        self.label_16.setText(_translate("MainWindow", "dt"))
        self.dmp_dt_param_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 0.008"))
        self.label_17.setText(_translate("MainWindow", "K"))
        self.dmp_K_param_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 100"))
        self.label_18.setText(_translate("MainWindow", "D"))
        self.dmp_D_param_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 1"))
        self.label_19.setText(_translate("MainWindow", "# basis_func"))
        self.dmp_basisfunc_param_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 20 per second of recording"))
        self.label_20.setText(_translate("MainWindow", "name of recording"))
        self.label_21.setText(_translate("MainWindow", "name of output file"))
        self.save_name_dmp_lineedit.setPlaceholderText(_translate("MainWindow", "Default: Same name as recording unless specified"))
        self.generate_DMP_button.setText(_translate("MainWindow", "Generate DMP"))
        self.Tab.setTabText(self.Tab.indexOf(self.Generate_tab), _translate("MainWindow", "Learning"))
        self.label_23.setText(_translate("MainWindow", "Set active DMP"))
        self.set_active_DMP_pushButton.setText(_translate("MainWindow", "set_active_dmp"))
        self.label_25.setText(_translate("MainWindow", "Initial position (in radians)"))
        self.label_6.setText(_translate("MainWindow", "shoulder_pan_joint"))
        self.set_JointState_init_0_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_8.setText(_translate("MainWindow", "shoulder_lift_joint"))
        self.set_JointState_init_1_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_9.setText(_translate("MainWindow", "elbow_joint"))
        self.set_JointState_init_2_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_10.setText(_translate("MainWindow", "wrist_1_joint"))
        self.set_JointState_init_3_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_11.setText(_translate("MainWindow", "wrist_2_joint"))
        self.set_JointState_init_4_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_12.setText(_translate("MainWindow", "wrist_3_joint"))
        self.set_JointState_init_5_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.get_JS_init_robot_pushButton.setText(_translate("MainWindow", "Retrieve from Robot"))
        self.label_26.setText(_translate("MainWindow", "Goal Position (in radians)"))
        self.label_14.setText(_translate("MainWindow", "shoulder_pan_joint"))
        self.set_JointState_goal_0_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_13.setText(_translate("MainWindow", "shoulder_lift_joint"))
        self.set_JointState_goal_1_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_30.setText(_translate("MainWindow", "elbow_joint"))
        self.set_JointState_goal_2_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_31.setText(_translate("MainWindow", "wrist_1_joint"))
        self.set_JointState_goal_3_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_29.setText(_translate("MainWindow", "wrist_2_joint"))
        self.set_JointState_goal_4_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.label_32.setText(_translate("MainWindow", "wrist_3_joint"))
        self.set_JointState_goal_5_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.get_JS_goal_robot_pushButton.setText(_translate("MainWindow", "Retrieve from robot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jointspace_2), _translate("MainWindow", "Joint space"))
        self.label_27.setText(_translate("MainWindow", "Initial Pose (in meter)"))
        self.label_7.setText(_translate("MainWindow", "tran_x"))
        self.label_33.setText(_translate("MainWindow", "tran_y"))
        self.label_34.setText(_translate("MainWindow", "tran_z"))
        self.label_35.setText(_translate("MainWindow", "ori_x"))
        self.label_36.setText(_translate("MainWindow", "ori_y"))
        self.label_37.setText(_translate("MainWindow", "ori_z"))
        self.label_38.setText(_translate("MainWindow", "ori_w"))
        self.get_CS_init_robot_PB.setText(_translate("MainWindow", "Retrieve from Robot"))
        self.label_28.setText(_translate("MainWindow", "Goal Pose (in meter)"))
        self.label_42.setText(_translate("MainWindow", "tran_x"))
        self.label_45.setText(_translate("MainWindow", "tran_y"))
        self.label_41.setText(_translate("MainWindow", "tran_z"))
        self.label_40.setText(_translate("MainWindow", "ori_x"))
        self.label_44.setText(_translate("MainWindow", "ori_y"))
        self.label_39.setText(_translate("MainWindow", "ori_z"))
        self.label_43.setText(_translate("MainWindow", "ori_w"))
        self.get_CS_goal_robot_PB.setText(_translate("MainWindow", "Retrieve from Robot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cartesianSpace_2), _translate("MainWindow", "Cartesian Space"))
        self.execute_plan_pushButton.setText(_translate("MainWindow", "EXECUTE PLAN"))
        self.execute_collisionCheck_PB.setText(_translate("MainWindow", "Check collisions"))
        self.label_24.setText(_translate("MainWindow", "tau"))
        self.set_tau_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 1"))
        self.Tab.setTabText(self.Tab.indexOf(self.Execute_tab), _translate("MainWindow", "Execute"))
        self.label_4.setText(_translate("MainWindow", "Recording folder"))
        self.label_46.setText(_translate("MainWindow", "Weights folder"))
        self.Tab.setTabText(self.Tab.indexOf(self.Settings_tab), _translate("MainWindow", "Settings"))
        self.shutDownButton.setText(_translate("MainWindow", "Shutdown"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHome.setText(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

